### ISSUE TITLE
Add clippy support

### ISSUE THREAD

**Issue by u2** [citahub/cita-common#177]
* [x] cita-common-benches
* [x] cita-types
* [x] logger
* [x] panic_hook
* [x] worker
* [x] error
* [x] snappy
* [x] cita-directories
* [x] cita-crypto-trait
* [x] ethcore-bloom-journal
* [x] rlp
* [x] rlp_derive
* [x] authority_manage
* [x] pubsub_rabbitmq
* [x] pubsub_zeromq
* [x] pubsub_kafka
* [x] pubsub
* [x] blake2b
* [x] util
* [x] jsonrpc-types
* [x] cita-web3
* [x] hashable
* [x] cita-merklehash
* [x] db
* [x] cita-secp256k1
* [x] cita-ed25519
* [x] cita-sm2
* [x] cita-crypto
* [x] libproto
* [x] proof
* [x] tx_pool
* [x] jsonrpc-proto
* [x] engine

**Comment by chaoticlonghair** [comment]
I think this issue should be waiting for #179 .

**Comment by kaikai1024** [comment]
> I think this issue should be waiting for #179 .

So we can do this issue now?

**Comment by chaoticlonghair** [comment]
I'm afraid not. Life is not perfect, especially rust.

IMHO, since [this issue](https://github.com/stepancheg/rust-protobuf/issues/331), it is too difficult to add CI, now. (We have to modify the generated codes in `build.rs`.)

**Comment by kaikai1024** [comment]
> I'm afraid not. Life is not perfect, especially rust.
> 
> IMHO, since [this issue](https://github.com/stepancheg/rust-protobuf/issues/331), it is too difficult to add CI, now. (We have to modify the generated codes in `build.rs`.)

don't understand.  does #180 can help?

**Comment by kaikai1024** [comment]
Going to do it first. So i will check the details and get some help form you tomorrow. @yangby-cryptape

**Comment by chaoticlonghair** [comment]
I add clippy to CI (#209) and replace Travis CI by Circle CI (#210) to speed up.
But I skip to lint almost all packages, only keep one as an example.

Next, we can add lint check for each crate, one by one.

**Comment by kaikai1024** [comment]
> I add clippy to CI (#209) and replace Travis CI by Circle CI (#210) to speed up.
> But I skip to lint almost all packages, only keep one as an example.
> 
> Next, we can add lint check for each crate, one by one.

Cool

**Comment by kaikai1024** [comment]
* [x] cita-common-benches
* [x] cita-types
* [x] logger
* [x] panic_hook
* [x] worker
* [x] error
* [x] snappy
* [x] cita-directories
* [x] cita-crypto-trait
* [x] ethcore-bloom-journal
* [x] rlp
* [x] rlp_derive
* [x] authority_manage
* [x] pubsub_rabbitmq
* [x] pubsub_zeromq
* [x] pubsub_kafka
* [x] pubsub
* [ ] blake2b
* [ ] util
* [ ] jsonrpc-types
* [ ] cita-web3
* [ ] hashable
* [ ] cita-merklehash
* [ ] db
* [ ] cita-secp256k1
* [ ] cita-ed25519
* [ ] cita-sm2
* [ ] cita-crypto
* [ ] libproto
* [ ] proof
* [ ] tx_pool
* [ ] jsonrpc-proto
* [ ] engine

**Comment by kaikai1024** [comment]
#224
