### ISSUE TITLE
`cargo build` cause some errors

### ISSUE THREAD

**Issue by classicalliu** [citahub/cita-common#212]
I run `cargo build` and get some errors, the version is `e07ebc3`, even when I copied [`env.sh`](https://github.com/cryptape/cita/blob/develop/env.sh) from CITA and run `./env.sh` to use docker.

![image](https://user-images.githubusercontent.com/13375784/53239137-3749de80-36d6-11e9-9998-d36e6b1c7e70.png)

**Comment by chaoticlonghair** [comment]
You have to specify features for each crate.
But different crates has different features.
So, you can not run `cargo build` at top of workspace.

**Comment by classicalliu** [comment]
> You have to specify features for each crate.
> But different crates has different features.
> So, you can not run `cargo build` at top of workspace.

Soga

**Comment by chaoticlonghair** [comment]
> Soga

Typo in this comment. More explanation can found [HERE](https://www.zhihu.com/question/35595362).
