### ISSUE TITLE
Message Refactor: flattening message

### ISSUE THREAD

**Issue by chaoticlonghair** [citahub/cita-common#8]
* Remove redundant data and worthless functions.
  * Remove redundant enum MsgType and worthless functions (`topic_to_string`, `id_to_key`, `de_cmd_id`, `display_cmd`).
  * Remove cmd_id (submodules and topics) from communication messages. 
* Make code more readable.
  * Change global functions for communication message to be class functions.
  * Use the same name for same thing in different places.
  * Standardize routing keys (Use the format as `PublisherSubModule.ClassType`).
* Reduce uncompress and deserialize.
  * Use routing keys to distribute messages and detect types.
  * Use fixed-length format messages for communication (Set or get `Origin` and `OperateType` directly).
  * Parse SignedProposal directly.
* Others.
  * Implement convert traits for protos.
  * Lots traits or functions will be generated automatically by a script.
  * Move all generated source codes into a separated directory.
  * Add some unit tests.

**Comment by u2** [comment]
I don't think so. Why remove message?
In the message struct,
```
pub struct Message { 
     // message fields 
     pub cmd_id: u32, 
     pub field_type: MsgType, 
     pub origin: u32, 
     pub operate: OperateType, 
     pub content: ::std::vec::Vec<u8>, 
     // special fields 
     unknown_fields: ::protobuf::UnknownFields, 
     cached_size: ::protobuf::CachedSize, 
 } 
```
`cmd_id` is duplicated, can be deleted;
`filed_type` is the content type, required;
`origin` is the origin submodule, required;
`operate` is uesless currently, can be deleted.
